// File: blink.v
// Generated by MyHDL 0.10
// Date: Sat Oct 19 11:14:41 2019


`timescale 1ns/10ps

module blink (
    clock,
    enable,
    led
);


input clock;
input enable;
output led;
wire led;

reg [11:0] countor;



always @(posedge clock) begin: inc
    if (enable) begin
        countor <= (countor + 1'b1);
    end
end



assign led = countor[4'b11];

endmodule
